Migrate to f string.
GetStream/stream-chat-python pull request #48
Opened 2020-12-11 04:58 UTC by ShreehariVaasishta

# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [x] Code changes are tested (add some information if not applicable)

## Description of the pull request
As per issue #45, migrating to f string.

2020-12-14 12:42 UTC, ferhatelmas commented on stream_chat/async_chat/channel.py
> +        return await self.client.post("{self.url}/truncate")
f

2020-12-14 12:42 UTC, ferhatelmas commented on stream_chat/async_chat/channel.py
> +        return await self.client.post("{self.url}/read", data=payload)
f

2020-12-14 12:44 UTC, ferhatelmas requested changes
Thanks for PR.

Could you see the comments and fix them too ?

2020-12-17 15:35 UTC, ShreehariVaasishta commented
Sure

2020-12-17 20:50 UTC, ferhatelmas approved these changes
LGTM

2020-12-17 20:50 UTC, merged